import { access, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Manifest } from "@vibe/shared";

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Ensure the build context has a Dockerfile. If the app brings its own
 * (adapter custom-dockerfile, or a Dockerfile is present), use it.
 * Otherwise generate one from the declared runtime adapter.
 *
 * Returns the Dockerfile filename relative to the context dir.
 */
export async function ensureDockerfile(
  contextDir: string,
  manifest: Manifest
): Promise<{ dockerfile: string; generated: boolean }> {
  const declared = manifest.runtime.dockerfile ?? "Dockerfile";

  if (await exists(join(contextDir, declared))) {
    return { dockerfile: declared, generated: false };
  }
  if (manifest.runtime.adapter === "custom-dockerfile") {
    throw new Error(
      `adapter is custom-dockerfile but '${declared}' was not found in the build context`
    );
  }

  const generated = generateDockerfile(manifest);
  const name = "Dockerfile.vibe";
  await writeFile(join(contextDir, name), generated, "utf8");
  return { dockerfile: name, generated: true };
}

function generateDockerfile(m: Manifest): string {
  const port = m.runtime.port;
  const pm = m.runtime.packageManager ?? "npm";
  // Only build if the app declares a build command — don't invent one.
  const build = m.runtime.buildCommand;
  const start = m.runtime.startCommand ?? defaultStart(m);
  const install = installCmd(pm);

  switch (m.runtime.adapter) {
    case "static-site":
      return staticDockerfile(m, build);
    case "node-next":
    case "node-vite-react":
    case "node-express":
    default:
      return [
        `# Generated by Vibe Base for adapter '${m.runtime.adapter}'`,
        `FROM node:22-slim`,
        `WORKDIR /app`,
        `COPY package*.json ./`,
        `RUN ${install}`,
        `COPY . .`,
        build ? `RUN ${build}` : `# no build step`,
        `ENV PORT=${port}`,
        `EXPOSE ${port}`,
        `CMD ${start}`,
        ``,
      ].join("\n");
  }
}

function staticDockerfile(m: Manifest, build?: string): string {
  return [
    `# Generated by Vibe Base (static-site)`,
    `FROM node:22-slim AS build`,
    `WORKDIR /app`,
    `COPY package*.json ./`,
    `RUN ${installCmd(m.runtime.packageManager ?? "npm")}`,
    `COPY . .`,
    build ? `RUN ${build}` : `# no build step`,
    `FROM caddy:2-alpine`,
    `COPY --from=build /app/dist /usr/share/caddy`,
    `ENV PORT=${m.runtime.port}`,
    `CMD ["caddy", "file-server", "--listen", ":${m.runtime.port}", "--root", "/usr/share/caddy"]`,
    ``,
  ].join("\n");
}

function installCmd(pm: string): string {
  switch (pm) {
    case "bun":
      return "bun install";
    case "pnpm":
      return "corepack enable && pnpm install --frozen-lockfile";
    case "yarn":
      return "corepack enable && yarn install --frozen-lockfile";
    default:
      return "npm ci || npm install";
  }
}

function defaultStart(m: Manifest): string {
  const pm = m.runtime.packageManager ?? "npm";
  const run = pm === "bun" ? "bun run" : pm === "npm" ? "npm run" : `${pm} run`;
  return `["sh","-c","${run} start"]`;
}
