import type { Manifest } from "./manifest.js";

/**
 * Generate a Dockerfile from a manifest's runtime adapter. Single source of
 * truth shared by the control plane (build-on-VPS) and the CLI (scaffolding a
 * Dockerfile into a GitHub repo so Actions can build the image).
 *
 * Apps with adapter "custom-dockerfile" bring their own Dockerfile and should
 * not be passed here.
 */
export function generateDockerfile(m: Manifest): string {
  const port = m.runtime.port;
  const pm = m.runtime.packageManager ?? "npm";
  // Only build if the app declares a build command — don't invent one.
  const build = m.runtime.buildCommand;
  const start = m.runtime.startCommand ?? defaultStart(m);
  const install = installCmd(pm);

  switch (m.runtime.adapter) {
    case "static-site":
      return staticDockerfile(m, build);
    case "node-next":
    case "node-vite-react":
    case "node-express":
    default:
      return [
        `# Generated by Vibe Base for adapter '${m.runtime.adapter}'`,
        `FROM node:22-slim`,
        `WORKDIR /app`,
        `COPY package*.json ./`,
        `RUN ${install}`,
        `COPY . .`,
        build ? `RUN ${build}` : `# no build step`,
        `ENV PORT=${port}`,
        `EXPOSE ${port}`,
        `CMD ${start}`,
        ``,
      ].join("\n");
  }
}

function staticDockerfile(m: Manifest, build?: string): string {
  return [
    `# Generated by Vibe Base (static-site)`,
    `FROM node:22-slim AS build`,
    `WORKDIR /app`,
    `COPY package*.json ./`,
    `RUN ${installCmd(m.runtime.packageManager ?? "npm")}`,
    `COPY . .`,
    build ? `RUN ${build}` : `# no build step`,
    `FROM caddy:2-alpine`,
    `COPY --from=build /app/dist /usr/share/caddy`,
    `ENV PORT=${m.runtime.port}`,
    `CMD ["caddy", "file-server", "--listen", ":${m.runtime.port}", "--root", "/usr/share/caddy"]`,
    ``,
  ].join("\n");
}

function installCmd(pm: string): string {
  switch (pm) {
    case "bun":
      return "bun install";
    case "pnpm":
      return "corepack enable && pnpm install --frozen-lockfile";
    case "yarn":
      return "corepack enable && yarn install --frozen-lockfile";
    default:
      return "npm ci || npm install";
  }
}

function defaultStart(m: Manifest): string {
  const pm = m.runtime.packageManager ?? "npm";
  const run = pm === "bun" ? "bun run" : pm === "npm" ? "npm run" : `${pm} run`;
  return `["sh","-c","${run} start"]`;
}
